# -*- coding: utf-8 -*-
"""NASA Nearest Earth Objects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyEKQdtgyoK1aELJSrgQWN9ztj3qKUT5
"""

library(tidyverse)

data <- read.csv("neo.csv", header=TRUE, stringsAsFactors=FALSE)

str(data)

ggplot(data = data) + 
  geom_point(mapping = aes(x = absolute_magnitude, y = miss_distance, color = hazardous))

# left
ggplot(data = data) + 
  geom_point(mapping = aes(x = absolute_magnitude, y = est_diameter_min))

# right
ggplot(data = data) + 
  geom_smooth(mapping = aes(x = absolute_magnitude, y = est_diameter_min))

ggplot(data = data, mapping = aes(x = relative_velocity, y = miss_distance)) + 
  geom_boxplot()